name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    continue-on-error: ${{ matrix.experimental }}
    
    strategy:
      matrix:
        include:
          - mediawiki_version: 1.35
            database_type: mysql
            experimental: false
          - mediawiki_version: 1.36
            database_type: mysql
            experimental: true

    container:
      image: gesinn/docker-mediawiki:${{ matrix.mediawiki_version }}
      options: --link some-${{ matrix.database_type }}:${{ matrix.database_type }}

    env:
      EXT_NAME: SemanticMediaWiki
      MW_INST_PATH: /var/www/html
      MW_EXT_PATH: /var/www/html/extensions
      DB_ROOT_USER: root
      DB_ROOT_PWD: database
      MW_DB_TYPE: ${{ matrix.database_type }}
      MW_DB_SERVER: ${{ matrix.database_type }}

    services:
      some-mysql:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: ${{ env.DB_ROOT_PWD }}
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 5

    steps:
      - name: Remove LocalSettings
        run: |
          rm ${{ env.MW_INST_PATH }}/LocalSettings.php

      - name: Reinstall MediaWiki
        run: >
          php ${{ env.MW_INST_PATH }}/maintenance/install.php
          --pass=wiki4everyone
          --server="http://localhost:8080"
          --scriptpath=""
          --dbtype=${{ env.MW_DB_TYPE }}
          --dbserver=${{ env.MW_DB_SERVER }}
          --installdbuser=${{ env.DB_ROOT_USER }}
          --installdbpass=${{ env.DB_ROOT_PWD }}
          --dbname=wiki
          --dbuser=wiki
          --dbpass=wiki
          --dbpath=/var/www/data
          wiki WikiSysop

      - name: Enable Debug Output
        run: |
          echo 'error_reporting(E_ALL| E_STRICT);' >> ${{ env.MW_INST_PATH }}/LocalSettings.php
          echo 'ini_set("display_errors", 1);' >> ${{ env.MW_INST_PATH }}/LocalSettings.php
          echo '$wgShowExceptionDetails = true;' >> ${{ env.MW_INST_PATH }}/LocalSettings.php
          echo '$wgDevelopmentWarnings = true;' >> ${{ env.MW_INST_PATH }}/LocalSettings.php
          echo '$wgEnableJavaScriptTest = true;' >> ${{ env.MW_INST_PATH }}/LocalSettings.php

      - name: Checkout Extension
        uses: actions/checkout@v2
        with:
          repository: SemanticMediaWiki/${{ env.EXT_NAME }}
          path: ${{ env.EXT_NAME }}

      # Setting actions/checkout@v2 path to env.MW_EXT_PATH fails with "Repository path '/var/www/html/extensions' is not under ..."
      # See also open PR https://github.com/actions/checkout/pull/388
      - name: Move Extension
        run: |
          mkdir -p ${{ env.MW_EXT_PATH }}
          mv ${{ env.EXT_NAME }} ${{ env.MW_EXT_PATH }}

      - name: Install SemanticMediaWiki
        run: |
          COMPOSER=composer.local.json composer require --no-update --working-dir ${{ env.MW_INST_PATH }} mediawiki/semantic-media-wiki @dev
          COMPOSER=composer.local.json composer config repositories.semantic-media-wiki '{"type": "path", "url": "extensions/SemanticMediaWiki"}' --working-dir ${{ env.MW_INST_PATH }}
          composer update --working-dir ${{ env.MW_INST_PATH }}
          echo "enableSemantics( 'localhost' );" >> ${{ env.MW_INST_PATH }}/LocalSettings.php
          tail -n5 ${{ env.MW_INST_PATH }}/LocalSettings.php
          php ${{ env.MW_INST_PATH }}/maintenance/update.php --quick

      - name: Run Tests
        run: >
          composer phpunit
          --working-dir ${{ env.MW_INST_PATH }}/extensions/SemanticMediaWiki
